/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TracksRouteImport } from './routes/tracks'
import { Route as AlbumsIndexRouteImport } from './routes/albums.index'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums.$albumId'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists.$artistId'
import { Route as GenresIndexRouteImport } from './routes/genres.index'
import { Route as GenresGenreRouteImport } from './routes/genres.$genre'
import { Route as PlaylistsIndexRouteImport } from './routes/playlists.index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists.$playlistId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TracksRoute = TracksRouteImport.update({
  id: '/tracks',
  path: '/tracks',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsIndexRoute = AlbumsIndexRouteImport.update({
  id: '/albums/',
  path: '/albums/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresIndexRoute = GenresIndexRouteImport.update({
  id: '/genres/',
  path: '/genres/',
  getParentRoute: () => rootRouteImport,
} as any)
const GenresGenreRoute = GenresGenreRouteImport.update({
  id: '/genres/$genre',
  path: '/genres/$genre',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIndexRoute = PlaylistsIndexRouteImport.update({
  id: '/playlists/',
  path: '/playlists/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tracks': typeof TracksRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tracks': typeof TracksRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/albums': typeof AlbumsIndexRoute
  '/artists': typeof ArtistsIndexRoute
  '/genres': typeof GenresIndexRoute
  '/playlists': typeof PlaylistsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/tracks': typeof TracksRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/genres/$genre': typeof GenresGenreRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/albums/': typeof AlbumsIndexRoute
  '/artists/': typeof ArtistsIndexRoute
  '/genres/': typeof GenresIndexRoute
  '/playlists/': typeof PlaylistsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/search'
    | '/settings'
    | '/tracks'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/genres/$genre'
    | '/playlists/$playlistId'
    | '/albums/'
    | '/artists/'
    | '/genres/'
    | '/playlists/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/favorites'
    | '/search'
    | '/settings'
    | '/tracks'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/genres/$genre'
    | '/playlists/$playlistId'
    | '/albums'
    | '/artists'
    | '/genres'
    | '/playlists'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/search'
    | '/settings'
    | '/tracks'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/genres/$genre'
    | '/playlists/$playlistId'
    | '/albums/'
    | '/artists/'
    | '/genres/'
    | '/playlists/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  TracksRoute: typeof TracksRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  GenresGenreRoute: typeof GenresGenreRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  AlbumsIndexRoute: typeof AlbumsIndexRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
  GenresIndexRoute: typeof GenresIndexRoute
  PlaylistsIndexRoute: typeof PlaylistsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tracks': {
      id: '/tracks'
      path: '/tracks'
      fullPath: '/tracks'
      preLoaderRoute: typeof TracksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/': {
      id: '/albums/'
      path: '/albums'
      fullPath: '/albums/'
      preLoaderRoute: typeof AlbumsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/': {
      id: '/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/': {
      id: '/genres/'
      path: '/genres'
      fullPath: '/genres/'
      preLoaderRoute: typeof GenresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/genres/$genre': {
      id: '/genres/$genre'
      path: '/genres/$genre'
      fullPath: '/genres/$genre'
      preLoaderRoute: typeof GenresGenreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/': {
      id: '/playlists/'
      path: '/playlists'
      fullPath: '/playlists/'
      preLoaderRoute: typeof PlaylistsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  TracksRoute: TracksRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  GenresGenreRoute: GenresGenreRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  AlbumsIndexRoute: AlbumsIndexRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
  GenresIndexRoute: GenresIndexRoute,
  PlaylistsIndexRoute: PlaylistsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
